<project><modelVersion>4.0.0</modelVersion><groupId>com.gunk</groupId><artifactId>java-service-fixture</artifactId><version>1.0.0</version><dependencies><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency><dependency><groupId>com.sendgrid</groupId><artifactId>sendgrid-java</artifactId><version>4.10.2</version></dependency></dependencies></project>
